- name: Create a Success Notification card
  office_365_connector_card:
    webhook: "{{ teams_webhook }}"
    summary: This is the notification for bamboo
    title: "{{ bamboo_deploy_project }} {{ bamboo_deploy_release }} was successfully deployed to {{ bamboo_deploy_environment }}"
    color: 228b22
    sections:
    - title: "Release **{{ bamboo_deploy_release }}**"
      activity_image: https://eus1-urlp.secure.skypeassets.com/contentapi1/3e8130fd-d05a-4106-8b64-e76e171e710f
      activity_title: "**{{ bamboo_deploy_environment }}** status update"
      activity_subtitle: Notified by Ansible
      activity_text: Previous version **{{ bamboo_deploy_previous_release }}**
      actions:
      - "@type": OpenUri
        name: View App
        targets:
        - os: default
          uri: "{{ bamboo_appUrl }}"
  when: 
    - bamboo_deploy_rollback == 'false'
    - teams_webhook != 'https://outlook.office.com/webhook/xx/IncomingWebhook/xxxx'

- name: Create a Success Notification card when is a rollback
  office_365_connector_card:
    webhook: "{{ teams_webhook }}"
    summary: This is the notification for bamboo
    title: "{{ bamboo_deploy_project }} RollBack was successfully deployed to {{ bamboo_deploy_environment }}"
    color: FFD700
    sections:
    - title: "Release **{{ bamboo_deploy_release }}**"
      activity_image: https://eus1-urlp.secure.skypeassets.com/contentapi1/3e8130fd-d05a-4106-8b64-e76e171e710f
      activity_title: "**{{bamboo_deploy_environment }}** status update"
      activity_subtitle: Notified by Ansible
      activity_text: Previous version **{{ bamboo_deploy_previous_release }}**
      actions:
      - "@type": OpenUri
        name: View App
        targets:
        - os: default
          uri: "{{ bamboo_appUrl }}"
  when: 
    - bamboo_deploy_rollback == 'true'
    - teams_webhook != 'https://outlook.office.com/webhook/xx/IncomingWebhook/xxxx'